---
- hosts: localhost
  vars_files:
    - settings.yml
    - ['/srv/git/saltbox/accounts.yml', '/srv/git/saltbox/defaults/accounts.yml.default']
    - ['/srv/git/saltbox/settings.yml', '/srv/git/saltbox/defaults/settings.yml.default']
    - ['/srv/git/saltbox/adv_settings.yml', '/srv/git/saltbox/defaults/adv_settings.yml.default']
  roles:
    - { role: pre_tasks }
    - { role: myrole, tags: ['myrole'] }
    - { role: crowdsec, tags: ['crowdsec'] }
    - { role: flame, tags: ['flame'] }
    - { role: gaps, tags: ['gaps'] }
    - { role: helloworld, tags: ['helloworld'] }
    - { role: haos, tags: ['haos'] }
    - { role: puddletag, tags: ['puddletag'] }
    - { role: spotweb, tags: ['spotweb'] }
    - { role: tqm, tags: ['tqm'] }
